### ISSUE TITLE
Error while running any python  file, pymobiledevice.lockdown & ak_vendor.usbmux  error

### ISSUE THREAD

**Issue by omkarzunjurke** [appknox/pymobiledevice#2]
Hello Dilip,
As I am going through it I tried to install it. It install properly but how to use it to fetch the device information while running any .py file it gives me error in 

from pymobiledevice.lockdown import LockdownClient
from ak_vendor.usbmux import default_mux as mux

so where should I get these modules?

Thanks in advance.

**Comment by ChillarAnand** [comment]
Hi @omkarzunjurke,

You can get ak_vendor from https://github.com/appknox/vendor/

Please note that latest versions of ak-vendor doesn't support pymobiledevice. But you can still use pymobiledevice with old version(0.6.3) of ak-vendor.

You can install it using 

    pip install ak-vendor==0.6.3

**Comment by subho007** [comment]
@ChillarAnand can you put that as a requirements ?

**Comment by ChillarAnand** [comment]
@subho007  Fixed it in https://github.com/appknox/pymobiledevice/pull/3

@omkarzunjurke I hope that solved your issue. Feel free to reopen if you are facing any other problems.
